-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 27, 2024 at 11:53 PM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bom`
--

-- --------------------------------------------------------

--
-- Table structure for table `characters`
--

CREATE TABLE `characters` (
  `char_id` int(11) NOT NULL,
  `charName` varchar(45) NOT NULL,
  `charType` enum('Hero','Zero') NOT NULL,
  `firstSeen` varchar(60) NOT NULL,
  `verse` varchar(10) NOT NULL,
  `abstract` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `characters`
--

INSERT INTO `characters` (`char_id`, `charName`, `charType`, `firstSeen`, `verse`, `abstract`) VALUES
(1, 'Nephi', 'Hero', '1 Nephi', '', 'Son of Lehi.  Righteous and knows his father to be a true prophet.  Repeatedly calls upon the Lord for wisdom and knowledge. Builds the boat that brings his family to the new lands.  During the time in the wilderness, he marries and has children.  The name of his wife, the name and number of his children, is never given.'),
(2, 'Lehi', 'Hero', '1 Nephi', '', 'Father of Nephi, Laman, Lemuel.  Leads his family out of Jerusalem and into the wilderness.'),
(3, 'Laman', 'Zero', '1 Nephi', '', 'Hard hearted non-believer who is constantly opposed to Nephi and regularly murmurs against Lehi.  Later a leader of the Lamanites.'),
(4, 'Sariah', 'Hero', '1 Nephi', '', 'Mother of Nephi.  Supportive of Lehi with one exception when Lehi sends the sons to retrieve the brass plates from Laban.'),
(5, 'Lemuel', 'Zero', '1 Nephi', '', 'Pretty much the same as Laman.  Generally complaining about all they left behind because of the &ldquo;. . .foolish imaginations of his [Lehi] heart.&rdquo; 1 Nephi 1:11'),
(6, 'Sam', 'Hero', '1 Nephi', '', 'The youngest brother to Nephi, Laman and Lemuel.  Not much of his own man but normally chooses to take Nephi&rsquo;s instruction and leadership.'),
(8, 'Laban', 'Zero', '1 Nephi', '', 'Powerful leader in Jerusalem.  Keeper of the brass plates.  When Nephi and his brothers attempt to make a deal to obtain the plates, Laban robs them.  He is delivered up by the spirit to Nephi who slays him with the &lsquo;Sword of Laban&rsquo;.'),
(9, 'Servants of Laban', 'Zero', '1 Nephi', '', 'Laban orders his servants to slay Nephi and his brothers when he sees the treasure they have brought in an attempt to obtain the brass plates.'),
(10, 'Angel Of The Lord', 'Hero', '1 Nephi', '', 'Visits the brothers in 4:29 and tells Laman and Lemuel that Nephi has been chosen by the Lord to be a ruler over them.  Commands them to go back to Laban who will be delivered unto them.'),
(11, 'Zoram', 'Hero', '1 Nephi', '', 'Servant of Laban who unwittingly helps Nephi obtain the brass plates and then take them out of the city.  Chooses to leave Jerusalem with Nephi.'),
(12, 'Ishmael', 'Hero', '1 Nephi', '', 'A member of the tribe of Ephraim.  He brings his family into the wilderness at the request of Lehi.  He dies in the wilderness and is buried in Nahom.'),
(13, 'Family Of Ishmael', 'Hero', '1 Nephi', '', 'Ishmael&rsquo;s family consists of his wife, two sons who have families of their own, and five daughters.  The two sons and their families, together with two of Ishmael&rsquo;s daughters, side with Laman and Lemuel against Nephi, Sam and Ismael, his wife and three of his daughters.  The three daughters who side with Nephi marry Nephi, Sam and Zoram'),
(14, 'Family Of Ishmael', 'Zero', '1 Nephi', '', 'Ishmael&rsquo;s family consists of his wife, two sons who have families of their own, and five daughters.  The two sons and their families, together with two of Ishmael&rsquo;s daughters, side with Laman and Lemuel against Nephi, Sam and Ismael, his wife and three of his daughters.  The three daughters who side with Nephi marry Nephi, Sam and Zoram'),
(15, 'Jacob', 'Hero', '1 Nephi', '', 'The elder of two sons born to Lehi during the time spent in the wilderness. Consecrated as a Priest by Nephi after the split from the Lamanites. The third book in the BOM contains his teachings to the Nephites.'),
(16, 'Joseph', 'Hero', '1 Nephi', '', 'The last child born to Lehi.  Born during the time spent in the wilderness. Consecrated as a Priest by Nephi after the split from the Lamanites.'),
(18, 'Sherem', 'Zero', 'Jacob', '', 'Appeared among the Nephites and preached there would be no Christ.  Leads many astray by his skilled manner of lies.  Is struck down by God and dies.'),
(19, 'Enos', 'Hero', 'Jacob', '', 'This son of Jacob is introduced at the end of Jacob when he is given the plates by his father. Enos writes a single chapter in which he prays that his brethren might be preserved and their records will be saved.'),
(20, 'Jarom', 'Hero', 'Jarom', '', 'Son of Enos. Like Enos, records only a single chapter. Gives a broad account of wars and contentions between the Nephites and Lamanites.  The Nephites become skilled in the production of weapons and have the Lord on their side which allows their smaller numbers to defeat the Lamanites.'),
(21, 'Omni', 'Hero', 'Jarom', '', 'Son of Jarom. Declares himself to be a wicked man, having not kept the commandments &ldquo;as I ought to have done.&rdquo;'),
(22, 'Amaron', 'Hero', 'Omni', '', 'Son of Omni. Declared that the &ldquo;more wicked part of the Nephites were destroyed&rdquo; so the words of the Lord could be verified: &ldquo;Inasmuch as ye will not keep my commandments ye shall not prosper in the land.&rdquo;'),
(23, 'Chemish', 'Hero', 'Omni', '', 'Brother of Amaron. Basically says nothing so gets the Hero rating simply because he&rsquo;s not seen to be a Zero.'),
(24, 'Abinadom', 'Hero', 'Omni', '', 'Son of Chemish. Briefly declares there have been many contentions between the Nephites and Lamanites.'),
(25, 'Amaleki', 'Hero', 'Omni', '', 'Son of Abinadom. Introduces Mosiah and tells how he discovered the people of Zarahemla who were another group brought out of Jerusalem by the Lord. Has no heir and so delivers the plates to Benjamin.'),
(26, 'Mosiah', 'Hero', 'Omni', '', 'Son of King Benjamin. Becomes king of Zarahemla. Interprets a stone brought before him by the people of Zarahemla which tells of Coriantumr.'),
(27, 'Coriantumr', 'Hero', 'Omni', '', 'Was found by the people of Zarahemla and lived with them for a time. Appears to be the remnant of another group of people whose first parents were brought out of Jerusalem at the time language was confounded.'),
(28, 'Benjamin', 'Hero', 'Omni', '', 'Son of Mosiah.  Becomes King Benjamin. Book of Mosiah covers his reign.  Book starts with the claim that there &ldquo;was no more contention in all the land&rdquo; during his reign. One of the great and mighty men of the BOM. A true believer and powerful preacher and leader. Delivers one of the most important sermons in the BOM at the time he handed the kingdom to Mosiah.'),
(29, 'Mormon', 'Hero', 'Words of Mormon', '', 'Father of Moroni. Made an abridgement of the plates of Nephi &ldquo;many hundreds of years after the coming of Christ&rdquo;'),
(30, 'Mosiah', 'Hero', 'Mosiah', '', 'Son of King Benjamin who named his first son after his own father. Becomes king of Zarahemla shortly before the death of Benjamin.'),
(31, 'Helorum', 'Zero', 'Mosiah', '', 'Nothing of import is written. Get&#039;s Zero title simply because he did nothing worth his inclusion beyond being named.'),
(32, 'Helaman', 'Zero', 'Mosiah', '', 'Nothing of import is written. Get&#039;s Zero title simply because he did nothing worth his inclusion beyond being named.'),
(33, 'Ammon', 'Hero', 'Mosiah', '', 'Mosiah appoints Ammon to lead a band of 16 men to search for the city of Lehi-Nephi in hopes of finding a group of Nephites who had left to journey there.'),
(34, 'Amaleki', 'Hero', 'Mosiah', '', 'Journeyed with Ammon in search of Lehi-Nephi.'),
(35, 'Helem', 'Hero', 'Mosiah', '', 'Journeyed with Ammon in search of Lehi-Nephi.'),
(36, 'Hem', 'Hero', 'Mosiah', '', 'Journeyed with Ammon in search of Lehi-Nephi.'),
(37, 'Limhi', 'Hero', 'Mosiah', '', 'King of land of Shilom. Son of Noah who was the son of Zeniff who led the people out of the land of Zarahemla. Initially puts Ammon, Helem and Hem in prison until he learns they are from Zarahemla. He then rejoices in the belief the Nephites will help him break the Lamanites&rsquo; hold over his people. They had been paying half their increase as tribute to the Lamanites since the time of the death of king Noah.  Limhi is king when the priests of Noah, who had been hiding in the wilderness, kidnap a number of Lamanite young women, thereby provoking a war.'),
(38, 'Zeniff', 'Hero', 'Mosiah', '', 'Led a band of Nephites out of Zarahemla and took possession of Lehi-Nephi and Shilom after making a deal with the Lamanite king. After 12 years king Laman fears their quickly growing strength and sends a host to attack them.  Zeniff leads his people to victory and passes away during a time of peace.'),
(39, 'Noah', 'Hero', 'Mosiah', '', 'Son of Zeniff.  A weak and worldly leader who leads his people in wickedness.  After capturing Abinadi, Noah allows his priests to question Abinadi, who withstands and rebukes them.'),
(40, 'Abinadi', 'Hero', 'Mosiah', '', 'Prophecies the need for repentance to the people during the reign of Noah.  King Noah seeks to slay Abinadi.  After completing delivery of his warnings on behalf of the Lord, Abinadi is put to death by fire.'),
(41, 'Alma', 'Hero', 'Mosiah', '', 'Is present when Abinadi confronts king Noah and his priests.  Pleads for Abinadi and then has to flee for his own life.  Records the words of Abinadi and then proceeds to teach them privately to the Nephites.  Baptizes many and eventually flees the kings army with &ldquo;about 450 souls.&rdquo;  After leading his group to a &ldquo;very beautiful and pleasant land,&rdquo; he refuses to be made king and convinces his people they should have no king but should glory in freedom and only have righteous men of god to teach them.'),
(42, 'Helam', 'Hero', 'Mosiah', '', 'Baptized by Alma in the wilderness at the Waters of Mormon.'),
(43, 'Gideon', 'Hero', 'Mosiah', '', 'An enemy of king Noah.  Engages in a fight with the king and is about to win when it becomes apparent the Lamanites are attacking.  Everybody flees.  A deal is made with the invading Lamanites that requires a tribute of half the possessions of Noah&rsquo;s kingdom as well as the king himself.  Gideon searches for the king only to discover he has been put to death by fire at the hands of the people who were with him, thus fulfilling the prophecies of Abinadi.  When Noah&rsquo;s priests kidnap the Lamanite daughters, it is Gideon who figures out what happened.  He is later slain by Nehor - a teacher of false doctrine (Alma 1:9)'),
(44, 'Amulon', 'Zero', 'Mosiah', '', 'Leader of the priests of king Noah - the ones who fled into the wilderness with the daughters of the Lamanites.  Finds favor with the Lamanite king and is appointed a teacher and then ruler over the Nephites of Alma. He remembers Alma and begins to persecute Alma and his people in revenge for having to flee Noah&rsquo;s kingdom.  Commands the Nephites to quit praying to God and threatens to kill any who disobey.  This treatment results in the Lord bringing the Nephites into the wilderness and, eventually, to Zarahemla where King Mosiah resides.'),
(45, 'Laman', 'Zero', 'Mosiah', '', 'King of the Lamanites at the time of Alma.  Makes a deal with Alma and then fails to keep it.  Appoints Amulon to be the ruler over Alma&rsquo;s people.'),
(46, 'Alma', 'Hero', 'Mosiah', '27:8', 'Son of Alma during time of Mosiah.  Is traveling with four sons of Mosiah and persecuting members of the church when an angel appears to them.  Alma is struck dumb and helpless for a number of days before recovering.  Becomes a great missionary.  Is given custody of the plates by Mosiah and later becomes the first Chief Judge.'),
(47, 'Ammon', 'Hero', 'Mosiah', '27:8', 'Son of Mosiah who was persecuting members of the church with Alma.  After zealously preaching to the people of Zarahemla, they ask king Mosiah for permission to travel to the land of Nephi to preach to the Lamanites.'),
(48, 'Aaron', 'Hero', 'Mosiah', '27:8', 'Son of Mosiah who was persecuting members of the church with Alma.  When Mosiah prepares to step down as king, he inquires of the people who they desire for king and they request Aaron who declines in preference of preaching to the Lamanites in the lands of Nephi.'),
(49, 'Omner', 'Hero', 'Mosiah', '27:8', 'Son of Mosiah who was persecuting members of the church with Alma. Becomes converted and later teaches gospel to Lamanites in the lands of Lamoni and his father.'),
(50, 'Himni', 'Hero', 'Mosiah', '27:8', 'Son of Mosiah who was persecuting members of the church with Alma. Becomes converted and later teaches gospel to Lamanites in the lands of Lamoni and his father.'),
(51, 'Nehor', 'Zero', 'Alma', '1:2', 'Goes about preaching false doctrine.  Is confronted by Gideon who is then slain by Nehor.  Is judged by Alma, the chief judge, and sentenced to death.  Taken to the hill Manti and suffers &ldquo;an ignominious death.&rdquo;'),
(52, 'Amlici', 'Zero', 'Alma', '2:1', 'Follower after the order of Nehor.  Desires to be king.  When the people deny him, he organizes his followers who make him their king and then take up arms against the Nephites.  After a losing battle, the Amlicites join with the Lamanites in the land of Minon. Is slain by Alma after attacking the Nephites who were returning to Zarahemla to defend their homes against the joined forces of their enemies.'),
(53, 'Spies of Alma', 'Hero', 'Alma', '2:21', 'Zeram, Amnor, Manti, Limher - four spies sent by Alma to pursue and report on the location and activities of the Amlicites. They discover the joining of Amlicite and Lamanite forces.'),
(54, 'Nephihah', 'Hero', 'Alma', '4:17', 'Appointed Chief Judge by Alma at a time of growing wickedness.  Alma had been Chief Judge and High Priest so he appointed Nephihah in order to free himself of the duty of judge in order to focus on preaching for the sake of leading his people back to righteousness.'),
(55, 'Amulek', 'Hero', 'Alma', '8:21', 'Alma is commanded by an angel of the Lord to return to the city of Ammonihah to again preach to the people who had rejected his teachings.  When he arrives at the city he asks for food and shelter from Amulek who had been told by an angel to expect Alma.  Both men preach to the people of Ammonihah.  They are cast into prison and freed by the power of God.'),
(56, 'Zeezrom', 'Zero', 'Alma', '10:31', 'A lawyer in Ammonihah who becomes a chief accuser of Alma and Amulek.  He first offers Amulek silver to deny God and then asks questions designed to trap Amulek into contradicting his own testimony. He is first rebuked by Amulek and then by Alma. Alma 11:21 - &rdquo;&hellip;Zeezrom was a man who was expert in the devices of the devil&hellip;.&rdquo;  He later has a change of heart (Alma 14:6-7) and pleads with the people after Alma and Amulek are taken before the Chief Judge.  He converts and is baptized in Alma 15.'),
(57, 'Zeezrom', 'Hero', 'Alma', '10:31', 'A lawyer in Ammonihah who becomes a chief accuser of Alma and Amulek.  He first offers Amulek silver to deny God and then asks questions designed to trap Amulek into contradicting his own testimony. He is first rebuked by Amulek and then by Alma. Alma 11:21 - &rdquo;&hellip;Zeezrom was a man who was expert in the devices of the devil&hellip;.&rdquo;  He later has a change of heart (Alma 14:6-7) and pleads with the people after Alma and Amulek are taken before the Chief Judge.  He converts and is baptized in Alma 15.'),
(58, 'Antionah', 'Hero', 'Alma', '12:20', 'A chief ruler of the people in Ammonihah, he questions Alma about specific things taught by Amulek. Get&#039;s Hero label because of his curiosity, though it&#039;s never shown to bear fruit.'),
(59, 'Melchizedek', 'Hero', 'Alma', '13:14', 'An original High Priest to whom tithes were paid by Abraham.  A king over the land of Salem, his people were wicked.  He preached repentance and they did repent to the point that Melchizedek became known as the &lsquo;Prince of Peace&rsquo;.'),
(60, 'Zoram', 'Hero', 'Alma', '16:5', 'Chief captain of the Nephite army.  Takes his two sons to visit Alma seeking advice about an attempt to recover Nephites who had been taken captive by the Lamanites when they attacked Ammonihah.  Their mission was successful after they followed the words of Alma.  People who are under his influence later become apostates when he teaches them to worship idols.'),
(61, 'Zoram', 'Zero', 'Alma', '16:5', 'Chief captain of the Nephite army.  Takes his two sons to visit Alma seeking advice about an attempt to recover Nephites who had been taken captive by the Lamanites when they attacked Ammonihah.  Their mission was successful after they followed the words of Alma.  People who are under his influence later become apostates when he teaches them to worship idols.'),
(62, 'Lehi', 'Hero', 'Alma', '16:5', 'Son of Zoram'),
(63, 'Aha', 'Hero', 'Alma', '16:5', 'Son of Zoram'),
(64, 'Lamoni', 'Zero', 'Alma', '17:21', 'A Lamanite king in the land of Ismael.  Ammon is brought before him after entering Lamanite lands to preach unto the people.  He is impressed by Ammon and allows him to live as a servant in his lands.  When Ammon cleaves off the arms of men who are attempting to scatter the king&#039;s flocks, the king is impressed and allows Ammon to teach him about God.  He converts as a result.'),
(65, 'Lamoni', 'Hero', 'Alma', '17:21', 'A Lamanite king in the land of Ismael.  Ammon is brought before him after entering Lamanite lands to preach unto the people.  He is impressed by Ammon and allows him to live as a servant in his lands.  When Ammon cleaves off the arms of men who are attempting to scatter the king&#039;s flocks, the king is impressed and allows Ammon to teach him about God.  He converts as a result.'),
(66, 'Queen of Ishmael', 'Hero', 'Alma', '19:2', 'The wife of Lamoni.  She consults with Ammon regarding the king while he&rsquo;s in a coma after being overwhelmed by the Spirit of God.  Having been in a coma for two days, some are telling the queen to bury him but she asks Ammon and he tells her to wait as Lamoni will awaken the following day.  She places her faith in his words and, after the prophecy comes true, she converts.'),
(67, 'Abish', 'Hero', 'Alma', '19:16', 'Rallies the people to the house of the king after he awakens and the power of the Spirit comes upon all those in attendance.  Abish was converted years prior and knew the importance of what she was witnessing so immediately brought as many as she could so they could witness the power of the Spirit as well.  After gathering the people they are engaging in contention over whether they&rsquo;re witnessing good or evil so Abish takes the hand of the prostrate queen, who immediately awakens and sings praise to God.'),
(68, 'Brother of one slain by Ammon', 'Zero', 'Alma', '19:22', 'Finds Ammon prostrate and unresponsive on the floor at the king&#039;s house.  Angry that Ammon had slain his brother, he raises his sword to attack and falls dead.'),
(69, 'Aaron', 'Hero', 'Alma', '20:2', 'Brother of Ammon.  Is imprisoned in the land of Middoni.  Suffered much abuse and afflictions at the hands of the Lamanites.  Before being freed at the behest of Ammon and Lamoni, he travels to the city of Jerusalem to preach to the Amalekites who refuse his teachings.  He then travels to Middoni where Ammon and Lamoni find him in prison.  After release from prison he travels to the king, father of Lamoni, and preaches to him, resulting in the conversion of the king, queen, and all the household staff.'),
(70, 'Muloki', 'Hero', 'Alma', '20:2', 'Is imprisoned in the land of Middoni with Aaron and Ammah.  Suffered much abuse and afflictions at the hands of the Lamanites.  Before being freed from prison in Middoni, he travels, with Ammah, to Ani-Anti to preach where the people refuse his teachings.  He then travels to Middoni where Ammon and Lamoni find him in prison.'),
(71, 'Ammah', 'Hero', 'Alma', '20:2', 'Is imprisoned in the land of Middoni with Aaron and Muloki.  Suffered much abuse and afflictions at the hands of the Lamanites.  Before being freed from prison in Middoni, he travels, with Muloki, to Ani-Anti to preach where the people refuse his teachings.  He then travels to Middoni where Ammon and Lamoni find him in prison.'),
(72, 'Antiomno', 'Zero', 'Alma', '20:4', 'The king of Middoni and a friend of Lamoni.  He imprisoned Aaron, Muloki and Ammah.  His people are hard-hearted and cause the Nephite preachers to be cast into prison where they suffer many afflictions.'),
(73, 'Father of Lamoni', 'Zero', 'Alma', '20:8', 'While Ammon and Lamoni are journeying to Middoni, they meet Lamoni&rsquo;s father.  The father is angry with Lamoni when he hears where they&rsquo;re going and why.  When Lamoni refuses to follow his orders, he draws his sword intending to kill Lamoni.  After a brief argument, the king attempts to slay Ammon who injures the kings arm and leaves him unable to fight (20:20).  When Ammon spares the kings life for the promise that his brethren will be released and Lamoni should retain his own kingdom, the king is astonished and asks Ammon to return later with his brethren.'),
(74, 'Father of Lamoni', 'Hero', 'Alma', '20:8', 'While Ammon and Lamoni are journeying to Middoni, they meet Lamoni&rsquo;s father.  The father is angry with Lamoni when he hears where they&rsquo;re going and why.  When Lamoni refuses to follow his orders, he draws his sword intending to kill Lamoni.  After a brief argument, the king attempts to slay Ammon who injures the kings arm and leaves him unable to fight (20:20).  When Ammon spares the kings life for the promise that his brethren will be released and Lamoni should retain his own kingdom, the king is astonished and asks Ammon to return later with his brethren.'),
(75, 'Mother of Lamoni', 'Zero', 'Alma', '22:19', 'Discovers the king collapsed on the floor after he&rsquo;s taken up in the Lord by the teachings of Aaron.  She orders first her servants to slay Aaron and his brethren and then, when they refuse, she orders the servants to gather the people so they might slay them instead.  Becomes converted after Aaron revives the king.'),
(76, 'Mother of Lamoni', 'Hero', 'Alma', '22:19', 'Discovers the king collapsed on the floor after he&rsquo;s taken up in the Lord by the teachings of Aaron.  She orders first her servants to slay Aaron and his brethren and then, when they refuse, she orders the servants to gather the people so they might slay them instead.  Becomes converted after Aaron revives the king.'),
(77, 'Royal Servants to the parents of Lamoni', 'Hero', 'Alma', '22:19', 'They witness the teachings of Aaron to the king and refuse to slay him and his brethren after the queen discovers the king unresponsive on the floor, blaming Aaron for attacking him.  They proclaim Aaron to be mightier than all of them and are converted soon after.'),
(78, 'Anti-Nephi-Lehi', 'Hero', 'Alma', '24:3', 'Brother of Lamoni.  Is given the kingdom in the year the Lamanites began to make war on the Anti-Nephi-Lehi&rsquo;s who had converted to the church.  He speaks to his people, asking them to &ldquo;&hellip;stain our swords no more with the blood of our brethren.&rdquo;  The people are then slaughtered in large numbers by attacking Lamanites, many of whom have a change of heart as a result of the refusal to fight.'),
(79, 'Korihor', 'Zero', 'Alma', '30:12', 'Described in Alma 30:6 as Anti-Christ because, as is later stated in verse 12, he preaches that there will be no Christ.  He also preaches that the church consists of &lsquo;foolish traditions of your fathers.&rsquo;  He preaches his falsehoods in several parts of the land before being brought to Alma where Korihor demands a sign of the truth that \r\nGod exists. He gets his sign when he is struck dumb as Alma declared he would be if he continued to deny God.'),
(80, 'Giddonah', 'Hero', 'Alma', '30:23', 'High Priest in the land of Gideon.  He questions Korihor, asking why he teaches people their beliefs are false, leading them astray and stealing their joy.  When realizing that Korihor will not stop his ways, he has him bound and sent to Zarahemla to Alma and the Chief Judge.'),
(81, 'Helaman', 'Hero', 'Alma', '31:7', 'Eldest son of Alma. He takes over as the leader of the Church in chapter 45.'),
(82, 'Shiblon', 'Hero', 'Alma', '31:7', 'Son of Alma.  Went with Alma to preach to the apostate Zoramites.  Alma later (chapter 38) tells him to go forth and preach. In chapter 63 he&rsquo;s given possession of the plates.'),
(83, 'Corianton', 'Hero', 'Alma', '31:7', 'Son of Alma.  Went with Alma to preach to the apostate Zoramites. In Alma 39, Alma rebukes him for sinful living, particularly for adultery. Through chapters 39-42, Alma explains many details of the gospel, finally telling Corianton to go forth preaching and living as an example of righteousness.'),
(84, 'Zarahemna', 'Zero', 'Alma', '43:5', 'Son of Alma.  Went with Alma to preach to the apostate Zoramites. In Alma 39, Alma rebukes him for sinful living, particularly for adultery. Through chapters 39-42, Alma explains many details of the gospel, finally telling Corianton to go forth preaching and living as an example of righteousness.'),
(85, 'Moroni', 'Hero', 'Alma', '43:16', 'Chief Captain of the Nephite army that defended against the Lamanite army led by Zarahemna. Twenty five years old at the start of the war, he prepared his army with armor including breastplates, arm shields, head shields and thick clothing. He sent men to ask Alma to inquire of the Lord and was told of the Lamanite plans, allowing his army to intercept them.'),
(86, 'Lehi', 'Hero', 'Alma', '43:35', 'One of Moroni&rsquo;s captains.  He made first contact with the Lamanite army as they began to cross the river Sidon.  His men slay many Lamanites and push them across the river where the men of Moroni wait for them and slay many more. Later, he is Chief Captain in the city of Noah when the army of Amalickiah attempts to attack the Nephites.'),
(87, 'Amlickiah', 'Zero', 'Alma', '46:3', 'Wants to be king over the Nephites.  Organizes the people who are opposed to Helaman and his brothers, and their teachings. Is forced to flee into the wilderness when Moroni comes after him to prevent him from going to the Lamanites and stirring them up against the Nephites. Becomes king of the Lamanites through fierce corruption.'),
(88, 'Lehonti', 'Zero', 'Alma', '47:10', 'Leader of a band of Lamanites that refuse to go to battle against the Nephites at the order of the king of the Lamanites.  Amalickiah conspires with him to turn the men loyal to the king over to his side so that none would stand against Amalickiah when he stole the throne. After succeeding with the conspiracy to defeat the men loyal to the king, Lehonti is poisoned by Amalackiah.'),
(89, 'Morianton', 'Zero', 'Alma', '50:28', 'The leader of the Nephite land of Morianton. Presides over a contention regarding boundaries between Morianton and Lehi wherein the people of Morianton wrongfully lay claim to part of the land of Lehi. Is slain by Teancum when the army of Morianton tries to flee to and then take possession of lands to the north.'),
(90, 'Teancum', 'Hero', 'Alma', '50:35', 'Captain of the army of Moroni who intercepts the army of Morianton on the borders of the land of Desolation.  Slays Morianton and defeats the army before forcing a covenant of peace from the people of Morianton. Later, in chapter 51, he heads off the army of Amalickiah on the border of the land Bountiful.  He sneaks into the Lamanite camp after a day of fierce battle and slays Amalickiah by stabbing him in the heart with a spear.'),
(91, 'Nehpihah', 'Hero', 'Alma', '50:37', 'The second chief judge, in the 25th year of the reign of the judges.  He &ldquo;filled the judgment-seat with perfect uprightness before God. (Verse 37)&rdquo;'),
(92, 'Pahoran', 'Hero', 'Alma', '50:39', 'Son of Nephihah.  He&rsquo;s given the second chief judge position upon the death of his father.  He refuses to alter, or allow alterations to, the law at the request of men who desire to have a king appointed.  In chapters 59-60 he draws the ire of Moroni when help is needed to resist Lamanite attacks but none is given.  It turns out that no help is sent because Pahoran is also defending against attacks.'),
(93, 'King-Men', 'Hero', 'Alma', '51:2', 'An unnamed group of nobles and elites who desire to end the free government and install a king as leader over the Nephites.  They are either slain, thrown in prison or compelled to fight for freedom by the army of Moroni.  (First mentioned in verse 2 but named by the title &ldquo;King-Men&rdquo; in verse 5)'),
(94, 'Ammoron', 'Zero', 'Alma', '52:3', 'Brother of Amalickiah.  He&rsquo;s appointed king of the Lamanites after the death of Amalickiah.  Seeks to retain the cities captured from the Nephites. Later negotiates with Moroni for a prisoner exchange.  Demands that the Nephites lay down their weapons and become subject to the Lamanites.'),
(95, 'Jacob', 'Zero', 'Alma', '52:20', 'Leader of the Lamanite army in the city of Mulek. Is killed in verse 35 after facing the army of Moroni in battle while trying to return to the city of Mulek, which had been recaptured by Moroni.'),
(96, 'Stripling Warriors', 'Hero', 'Alma', '53:16', 'Sons of the Lamanites who became Nephites and covenanted to lay down their weapons and never fight again. The sons numbered 2000 and were led by Helaman in battle. Chapter 56 tells how they fight with miraculous power and none are slain in battle against a greater force of Lamanites.'),
(97, 'Laman', 'Hero', 'Alma', '55:5', 'A descendant of Laman, he was a servant of the king who was murdered by Amalickiah. Moroni sends him, along with a small group of warriors, into the city of Gid where Nephite prisoners are being held by Ammoron. Laman and his men deceive the guards by claiming they&rsquo;ve escaped from the Nephites and stolen wine before fleeing.  The guards become drunk and Moroni sneaks weapons into the city to arm the Nephite prisoners while having his army surround the city from outside.  When the Lamanites realize what has happened they surrender the city back to Moroni.'),
(98, 'Antipus', 'Hero', 'Alma', '56:9', 'Leader of the Nephite army in the city of Judea.  His forces are reinforced by Helaman and the Stripling Warriors.  Coordination between Antipus and Helaman results in the main Lamanite army being defeated.'),
(99, 'Gid', 'Hero', 'Alma', '57:28', 'Chief captain of a group that was tasked with delivering Lamanite prisoners to the land of Zarahemla. The prisoners revolt and most are slain but some escape.  This frees Gid and his men to return to the city of Cumeni in time to defend it along with Helaman.  In chapter 58, Gid helps to defeat the Lamanite army in Manti.'),
(100, 'Teomner', 'Hero', 'Alma', '58:16', 'Helps Gid and Helaman to defeat the Lamanite army guarding the city of Manti.'),
(101, 'Pachus', 'Zero', 'Alma', '62:6', 'King of the Nephite dissenters - the one chosen by the King-Men first mentioned in Alma 51:2.  He and his followers drove Pahoran from the judgment-seat and out of Zarahemla.  He&rsquo;s quickly slain by the army raised by Moroni in support of Pahoran and freedom.'),
(102, 'Moronihah', 'Hero', 'Alma', '62:43', 'Son of Moroni.  He is given command of the Nephite armies when Moroni retires after defeating and chasing away the Lamanite armies.  He is able to slay Coriantumr when he marches on Bountiful, after capturing Zarahemla.  Later (Helaman 4)he fights back the Lamanites yet again and recaptures land lost to them when Nephite dissenters goad the Lamanites into attacking their former neighbors.'),
(103, 'Hagoth', 'Hero', 'Alma', '63:5', 'A Nephite who became a ship builder.  He built ships that Nephite voyagers used to attempt travel to distant areas.  Some ships return but many of the people are never heard from again.'),
(104, 'Helaman', 'Hero', 'Alma', '63:11', 'Son of Helaman. He&rsquo;s given the plates by Shiblon before his death.  Helaman takes the judgement-seat after the murder of Paanchi and the battles led by Coriantumr.'),
(105, 'Pahoran', 'Hero', 'Helaman', '1:3', 'Son of Pahoran who contended with his brothers to take the judgement-seat after the death of Pahoran.  He was the rightful heir but is murdered by Kishkumen who was a supporter of Paanchi.'),
(106, 'Paanchi', 'Zero', 'Helaman', '1:3', 'Son of Pahoran who contended with his brothers to take the judgement-seat after the death of Pahoran.  Paanchi instigated a rebellion in an attempt to gain the judgement-seat.  When he is sentenced to death for rebellion, his supporters send Kishkumen to kill Pahoran.  After the murder the seat is given to Pacumeni by the vote of the people.'),
(107, 'Pacumeni', 'Hero', 'Helaman', '1:3', 'Son of Pahoran who contended with his brothers to take the judgement-seat after the death of Pahoran.  Realizes that he cannot win so defers to the voice of the people and ceases to make claim to the judgement-seat.'),
(108, 'Kishkumen', 'Zero', 'Helaman', '1:9', 'Sent by followers of Paanchi to murder Pahoran as he sat upon the judgement-seat.  Many of the associates of Kishkumen are found and put to death.  He also attempts to murder Helaman when he assumes the judgement-seat.'),
(109, 'Coriantumr', 'Zero', 'Helaman', '1:15', 'A descendant of Zarahemla, he led an army against the Nephites.  Kills Pacumeni during the taking of the city of Zarahemla.'),
(110, 'Tubaloth', 'Zero', 'Helaman', '1:16', 'King of the Lamanites and descendant of Ammoron.  He sends Coriantumr and his men to battle against the Nephites.  They easily take the city of Zarahemla due to the Nephite government being in disarray.'),
(111, 'Gadianton', 'Zero', 'Helaman', '2:4', 'Leader of the band of Kishkumen.  He is expert in the craft of murder and robbery.  His group evolves into the Gadianton Robbers who wreak havoc across the land. Gadianton wishes to gain the judgement-seat so he sends Kishkumen to murder Helaman.  They eventually manage to take the Nephite government.'),
(112, 'Servant of Helaman', 'Hero', 'Helaman', '2:6', 'Never named except as the &ldquo;Servant of Helaman&rdquo;.  He intercepts Kishkumen as he attempts to slay Helaman.  The Servant stabs Kishkumen in the heart and quickly tells Helaman what he&rsquo;s done and learned.'),
(113, 'Nephi', 'Hero', 'Helaman', '3:21', 'Firstborn son of Helaman. He fills the judgement-seat and rules with integrity after the death of Helaman in the 53rd year of the reign of the judges. Encourages the Nephites to repent and humble themselves after being lifted up in pride.'),
(114, 'Lehi', 'Hero', 'Helaman', '3:21', 'Son of Helaman.  Preaches to the Nephites, along with Nephi and Moroniha.  Succeeds in bringing many to repentance. Is imprisoned with Nephi when a cloud of darkness and pillar of fire come upon them and their persecutors.  The event results in many converts who lay down their weapons of war and return seized Nephite lands to the rightful owners.'),
(115, 'Cezoram', 'Hero', 'Helaman', '5:1', 'Obtains the judgement-seat from Nephi when he retires in order to preach repentance unto the Nephites.  Is murdered by an unknown assailant in the 66th year of the reign of the judges.  His son (not named) is also murdered that same year.'),
(116, 'Aminadab', 'Zero', 'Helaman', '5:35', 'Originally a Nephite dissenter.  He sees the faces of Nephi and Lehi while everyone is engulfed in a cloud of darkness inside the prison where Nephi and Lehi are being held prior to their planned execution.  Aminadab calls everyone&rsquo;s attention to the prisoners who appear to be conversing with an unseen other.  Recognizing what&rsquo;s happening, Aminadab calls on the people to repent.'),
(117, 'Aminadab', 'Hero', 'Helaman', '5:35', 'Originally a Nephite dissenter.  He sees the faces of Nephi and Lehi while everyone is engulfed in a cloud of darkness inside the prison where Nephi and Lehi are being held prior to their planned execution.  Aminadab calls everyone&rsquo;s attention to the prisoners who appear to be conversing with an unseen other.  Recognizing what&rsquo;s happening, Aminadab calls on the people to repent.'),
(118, 'Judges belonging to the gang of Gadianton', 'Zero', 'Helaman', '8:1', 'Judges who assemble together with a crowd that comes to see Nephi when word spreads that he is on his tower crying out in apparent mourning.  When Nephi declares the law to be corrupt and the people to be wicked, the judges seek to turn the people against him.  After the murder of the chief judge, they accuse Nephi and try to cause him to confess to the slaying.'),
(119, 'Seezoram', 'Hero', 'Helaman', '9:23', 'The apparent successor to Cezoram, who was murdered.  Seezoram is also murdered, this crime being committed by his brother, Seantum.'),
(120, 'Seantum', 'Zero', 'Helaman', '9:26', 'Brother of Seezoram, the chief judge.  He murders his brother as Nephi accuses him of doing to the judges that had accused Nephi of the crime.  He first denies, then admits to the murder as Nephi prophesied he would do.'),
(121, 'The &ldquo;New&rdquo; robbers of Gadianton', 'Zero', 'Helaman', '11:26', 'The band of Gadianton has ceased to exist when wicked Lamanites and Nephite dissenters who live secretly in the wilderness band together as a loose group of thugs that seek out and find the secret plans of Gadianton.  Using Gadiantons ideas they make regular forays to murder and plunder, eventually becoming stronger than the combined armies of the Nephites and the Lamanites.'),
(122, 'Samuel', 'Hero', 'Helaman', '13:2', 'A righteous Lamanite who comes to Zarahemla to preach repentance.  After days of preaching, and constant rejection, he prepares to return home but the voice of the Lord commands him to stay and continue preaching &ldquo;whatsoever things should come into his heart.&rdquo; He is not allowed to enter the city so he climbs a wall and preaches from there. He proclaims signs of the coming of Christ before the unrepentant start launching projectiles in an attempt to kill him.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `characters`
--
ALTER TABLE `characters`
  ADD PRIMARY KEY (`char_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `characters`
--
ALTER TABLE `characters`
  MODIFY `char_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=123;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
